version: 2.1

jobs:

  nest-build:
    docker:
      - image: node:latest
    working_directory: ~/vidalog
    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - persist_to_workspace:
          root: ~/vidalog
          paths:
            - build
            - node_modules
      - run: echo "BUILD SUCCESS"
  docker-build-and-push:
    docker:
      - image: nginx:latest
    working_directory: ~/vidalog
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          
      - attach_workspace:
          at: ~/vidalog
      - run : cat /etc/issue
      - run : apt-get update
      - run : apt-get install apt-transport-https
      - run : apt-get install ca-certificates
      - run : apt-get install curl
      - run : apt-get install -y gnupg
      - run : apt-get install -y lsb-release
      - run : curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run : echo \
              "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian/dists/buster/$(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

      - run : apt-get update
      - run : apt-get install docker-ce docker-ce-cli containerd.io
      - run: |
          docker build -t yongwon0824/vidalog-frontend:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push yongwon0824/vidalog-frontend:latest
  deploy:
    machine: true
    steps:
      - checkout
      - run: ssh ec2-user@54.180.166.3 ./deploy-frontend.sh
  
orbs:
  docker: circleci/docker@1.6.0
  
workflows:
  version: 2.1
  build:
    jobs:
      - nest-build
      - docker-build-and-push:
          requires:
            - nest-build
          context:
            - DOCKER
      - deploy:
          requires:
            - docker-build-and-push
          context:
            - AWS
